"""extracted cell mapping

Revision ID: 18dcd56e0cd1
Revises: cbbcb72ceeeb
Create Date: 2026-08-13 15:44:05.626628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18dcd56e0cd1'
down_revision: Union[str, None] = 'cbbcb72ceeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_cell',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('cell_key', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('row_label', sa.String(length=500), nullable=False),
    sa.Column('data_point_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_point_id'], ['data_point.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'cell_key')
    )
    with op.batch_alter_table('extracted_cell', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_cell_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_cell_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_cell', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_cell_project_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_cell_document_id'))

    op.drop_table('extracted_cell')
    # ### end Alembic commands ###
