"""external call log and cache

Revision ID: 718e7a2941c8
Revises: 7f145560a630
Create Date: 2026-08-11 13:37:33.444639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '718e7a2941c8'
down_revision: Union[str, None] = '7f145560a630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=60), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'key_hash')
    )
    op.create_table('external_call_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model_role', sa.String(length=40), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('stage_id', sa.String(length=60), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('payload_bytes', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('est_cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_call_log_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_call_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_call_log_project_id'))

    op.drop_table('external_call_log')
    op.drop_table('cache_entry')
    # ### end Alembic commands ###
