"""foundation schema

Revision ID: 7f145560a630
Revises: 
Create Date: 2026-08-11 11:04:08.509900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f145560a630'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('formula_id', sa.String(length=100), nullable=False),
    sa.Column('formula_version', sa.String(length=40), nullable=False),
    sa.Column('engine_version', sa.String(length=40), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('input_quality_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_project_id'), ['project_id'], unique=False)

    op.create_table('data_point',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_kind', sa.String(length=40), nullable=False),
    sa.Column('current_revision_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_point_project_id'), ['project_id'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=1000), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sha256')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sha256'), ['sha256'], unique=False)

    op.create_table('extraction_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('acquisition_method', sa.String(length=40), nullable=False),
    sa.Column('extractor_id', sa.String(length=100), nullable=False),
    sa.Column('extractor_version', sa.String(length=40), nullable=False),
    sa.Column('model_role', sa.String(length=40), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_ref', sa.String(length=200), nullable=True),
    sa.Column('raw_response_ref', sa.String(length=200), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_record_project_id'), ['project_id'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=60), nullable=False),
    sa.Column('work_item_ref', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=300), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('parent_job_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_state'), ['state'], unique=False)

    op.create_table('workflow_issue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('issue_type', sa.String(length=60), nullable=False),
    sa.Column('work_item_ref', sa.String(length=200), nullable=False),
    sa.Column('stage_id', sa.String(length=60), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_issue', schema=None) as batch_op:
        batch_op.create_index('ix_workflow_issue_open_unique', ['work_item_ref', 'issue_type'], unique=True, sqlite_where=sa.text("state = 'OPEN'"))
        batch_op.create_index(batch_op.f('ix_workflow_issue_project_id'), ['project_id'], unique=False)

    op.create_table('document_page',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number')
    )
    with op.batch_alter_table('document_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_page_document_id'), ['document_id'], unique=False)

    op.create_table('parse_artifact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('parser_id', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'parser_id', 'parser_version', 'kind', 'input_hash')
    )
    with op.batch_alter_table('parse_artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parse_artifact_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parse_artifact_project_id'), ['project_id'], unique=False)

    op.create_table('stage_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=60), nullable=False),
    sa.Column('work_item_ref', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'work_item_ref')
    )
    with op.batch_alter_table('stage_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_state_project_id'), ['project_id'], unique=False)

    op.create_table('source_locator',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=True),
    sa.Column('table_number', sa.String(length=40), nullable=True),
    sa.Column('figure_number', sa.String(length=40), nullable=True),
    sa.Column('row_label', sa.String(length=500), nullable=True),
    sa.Column('column_label', sa.String(length=500), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('bbox_norm', sa.JSON(), nullable=True),
    sa.Column('bbox_native', sa.JSON(), nullable=True),
    sa.Column('parser_id', sa.String(length=100), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('parse_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['parse_artifact_id'], ['parse_artifact.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_locator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_locator_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_locator_project_id'), ['project_id'], unique=False)

    op.create_table('value_revision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('data_point_id', sa.String(length=36), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('value_normalized', sa.Numeric(asdecimal=False), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('scientific_basis', sa.String(length=40), nullable=False),
    sa.Column('acquisition_method', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('confidence_rule_id', sa.String(length=100), nullable=True),
    sa.Column('confidence_rule_version', sa.String(length=40), nullable=True),
    sa.Column('review_state', sa.String(length=40), nullable=False),
    sa.Column('source_locator_id', sa.String(length=36), nullable=True),
    sa.Column('extraction_record_id', sa.String(length=36), nullable=True),
    sa.Column('calculation_id', sa.String(length=36), nullable=True),
    sa.Column('verifiability', sa.String(length=60), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('researcher_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("review_state IN ('NOT_REVIEWED','REVIEW_REQUIRED','VERIFIED','CORRECTED','MARKED_UNCERTAIN','EXCLUDED')", name='ck_review_enum'),
    sa.CheckConstraint("scientific_basis != 'DERIVED' OR calculation_id IS NOT NULL", name='ck_derived_requires_calculation'),
    sa.CheckConstraint("scientific_basis IN ('SOURCE_REPORTED','DERIVED','INFERRED','UNRESOLVED')", name='ck_basis_enum'),
    sa.CheckConstraint("scientific_basis NOT IN ('SOURCE_REPORTED','INFERRED') OR source_locator_id IS NOT NULL", name='ck_source_requires_locator'),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ),
    sa.ForeignKeyConstraint(['data_point_id'], ['data_point.id'], ),
    sa.ForeignKeyConstraint(['extraction_record_id'], ['extraction_record.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['source_locator_id'], ['source_locator.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['value_revision.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_point_id', 'revision_no')
    )
    with op.batch_alter_table('value_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_value_revision_data_point_id'), ['data_point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_value_revision_project_id'), ['project_id'], unique=False)

    op.create_table('calculation_input',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('calculation_id', sa.String(length=36), nullable=False),
    sa.Column('data_point_id', sa.String(length=36), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculation.id'], ),
    sa.ForeignKeyConstraint(['data_point_id'], ['data_point.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['value_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculation_input', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calculation_input_calculation_id'), ['calculation_id'], unique=False)

    op.create_table('review_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('previous_revision_id', sa.String(length=36), nullable=True),
    sa.Column('new_revision_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action != 'CORRECT' OR previous_revision_id IS NOT NULL", name='ck_correct_requires_previous'),
    sa.ForeignKeyConstraint(['new_revision_id'], ['value_revision.id'], ),
    sa.ForeignKeyConstraint(['previous_revision_id'], ['value_revision.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_event_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_event_project_id'))

    op.drop_table('review_event')
    with op.batch_alter_table('calculation_input', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_input_calculation_id'))

    op.drop_table('calculation_input')
    with op.batch_alter_table('value_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_value_revision_project_id'))
        batch_op.drop_index(batch_op.f('ix_value_revision_data_point_id'))

    op.drop_table('value_revision')
    with op.batch_alter_table('source_locator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_locator_project_id'))
        batch_op.drop_index(batch_op.f('ix_source_locator_document_id'))

    op.drop_table('source_locator')
    with op.batch_alter_table('stage_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_state_project_id'))

    op.drop_table('stage_state')
    with op.batch_alter_table('parse_artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parse_artifact_project_id'))
        batch_op.drop_index(batch_op.f('ix_parse_artifact_document_id'))

    op.drop_table('parse_artifact')
    with op.batch_alter_table('document_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_page_document_id'))

    op.drop_table('document_page')
    with op.batch_alter_table('workflow_issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_issue_project_id'))
        batch_op.drop_index('ix_workflow_issue_open_unique', sqlite_where=sa.text("state = 'OPEN'"))

    op.drop_table('workflow_issue')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_state'))
        batch_op.drop_index(batch_op.f('ix_job_stage_id'))
        batch_op.drop_index(batch_op.f('ix_job_project_id'))

    op.drop_table('job')
    with op.batch_alter_table('extraction_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_record_project_id'))

    op.drop_table('extraction_record')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sha256'))
        batch_op.drop_index(batch_op.f('ix_document_project_id'))

    op.drop_table('document')
    with op.batch_alter_table('data_point', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_point_project_id'))

    op.drop_table('data_point')
    with op.batch_alter_table('calculation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calculation_project_id'))

    op.drop_table('calculation')
    op.drop_table('project')
    # ### end Alembic commands ###
