"""audit finding table

Revision ID: cbbcb72ceeeb
Revises: 718e7a2941c8
Create Date: 2026-08-11 15:27:44.838826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cbbcb72ceeeb'
down_revision: Union[str, None] = '718e7a2941c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('finding_kind', sa.String(length=40), nullable=False),
    sa.Column('taxonomy_code', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('certainty', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('detected_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_finding_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_finding_project_id'))

    op.drop_table('audit_finding')
    # ### end Alembic commands ###
